spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: dice-throne-398523:us-central1:dice-throne
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql:///dice-throne