spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: sa
    url: jdbc:postgresql://localhost:5432/dice-throne

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs